"""Proposal-only webnovel initialization protocol."""

from .errors import PlotInitError
from .hook_arbiter import (
    arbitrate_initialization_hook,
    is_initialization_meta_prompt,
    is_initialization_storage_path,
    resolve_initialization_intent,
)
from .lifecycle_adapter import proposal_to_lifecycle_package
from .advantages import (
    ADVANTAGE_SCHEMA_VERSION,
    ADVANTAGE_SIDECAR_PATH,
    advantage_package_from_artifact_manifest,
    advantage_package_from_frozen_proposal,
    advantage_package_has_typed_content,
    advantage_sidecar_reference,
    assert_advantage_sidecar_target_baseline,
    build_advantage_package,
    build_advantage_sidecar_artifact,
    recompute_advantage_package_hash,
    render_advantage_package,
    validate_advantage_package,
    verify_materialized_advantage_sidecar,
)
from .items import (
    ITEM_SCHEMA_VERSION,
    ITEM_SIDECAR_PATH,
    assert_item_sidecar_target_baseline,
    build_item_package,
    build_item_sidecar_artifact,
    item_package_from_artifact_manifest,
    item_package_from_frozen_proposal,
    item_package_has_typed_content,
    item_sidecar_reference,
    recompute_item_package_hash,
    render_item_package,
    validate_item_package,
    verify_materialized_item_sidecar,
)
from .normalized import (
    export_normalized_bundle,
    normalization_diff,
    normalized_hash,
    parse_normalized_export,
    render_normalized_bundle,
)
from .remote_cache import (
    MemoryRemoteResponseCache,
    RemoteCacheIdentity,
    RemoteResponseCache,
    SQLiteRemoteResponseCache,
    sanitize_remote_cache_value,
)
from .remote_model import (
    RemoteModelConfig,
    RemoteModelError,
    load_remote_model_config,
)
from .service import PlotInitService

__all__ = [
    "PlotInitError",
    "PlotInitService",
    "ITEM_SCHEMA_VERSION",
    "ITEM_SIDECAR_PATH",
    "ADVANTAGE_SCHEMA_VERSION",
    "ADVANTAGE_SIDECAR_PATH",
    "MemoryRemoteResponseCache",
    "RemoteCacheIdentity",
    "RemoteModelConfig",
    "RemoteModelError",
    "RemoteResponseCache",
    "SQLiteRemoteResponseCache",
    "arbitrate_initialization_hook",
    "assert_item_sidecar_target_baseline",
    "assert_advantage_sidecar_target_baseline",
    "advantage_package_from_artifact_manifest",
    "advantage_package_from_frozen_proposal",
    "advantage_package_has_typed_content",
    "advantage_sidecar_reference",
    "build_advantage_package",
    "build_advantage_sidecar_artifact",
    "build_item_package",
    "build_item_sidecar_artifact",
    "export_normalized_bundle",
    "is_initialization_meta_prompt",
    "is_initialization_storage_path",
    "item_package_from_artifact_manifest",
    "item_package_from_frozen_proposal",
    "item_package_has_typed_content",
    "item_sidecar_reference",
    "load_remote_model_config",
    "normalization_diff",
    "normalized_hash",
    "parse_normalized_export",
    "proposal_to_lifecycle_package",
    "recompute_item_package_hash",
    "recompute_advantage_package_hash",
    "render_normalized_bundle",
    "render_item_package",
    "render_advantage_package",
    "resolve_initialization_intent",
    "sanitize_remote_cache_value",
    "validate_item_package",
    "validate_advantage_package",
    "verify_materialized_item_sidecar",
    "verify_materialized_advantage_sidecar",
]
